"""Alter Doctor.specialization to SET_NULL on delete and allow nulls

Generated by assistant
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="specialization",
            field=models.ForeignKey(
                null=True, blank=True, on_delete=models.SET_NULL, to="core.specialization"
            ),
        ),
    ]
